export enum Storage {
    SELECTED_THEME = 'SELECTED_THEME',
    PROFILE_ID = 'PROFILE_ID',
    LANGUAGE_OPTIONS = 'LANGUAGE_OPTIONS',
    TOKEN = 'TOKEN',
    USER = 'USER',
    STAY_LOGGED_IN = 'STAY_LOGGED_IN',
    SELECTED_LAGUAGE = 'SELECTED_LAGUAGE',
}
